# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0132_realm_message_visibility_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='realm_names_in_subject',
            field=models.BooleanField(default=False),
        ),
    ]
