# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0133_realm_realm_names_in_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='realm_names_in_subject',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='realm_names_in_subject',
            field=models.BooleanField(default=False),
        ),
    ]
