# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0134_auto_20180106_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='realm_names_in_subject',
            new_name='realm_name_in_notifications',
        ),
    ]
