# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0133_rename_botuserconfigdata_botconfigdata'),
        ('zerver', '0135_auto_20180108_0018'),
    ]

    operations = [
    ]
